name: deploy via OIDC

on:
  push:
    branches:
      - 'main'

env:
  AZURE_RESOURCEGROUP_NAME: minecraft-rg

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run az deployment group what-if'
        run: |
          cd bicep-azure-minecraft
          az deployment group what-if --template-file main.bicep --mode Complete \
          --parameters objectId=1cbd6d17-3682-4175-9ba2-adb7582c3507 \
          --parameters userId=9ddd81b2-ebc6-498b-95bb-8ec7f57c7558az \
          --resource-group ${{ env.AZURE_RESOURCEGROUP_NAME }}
