name: deploy

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

env:
  AZURE_RESOURCEGROUP_NAME: minecraft-rg

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          template: ./bicep-azure-minecraft/main.bicep